# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.select_url = QtWidgets.QComboBox(self.centralwidget)
        self.select_url.setGeometry(QtCore.QRect(260, 100, 291, 22))
        self.select_url.setObjectName("select_url")
        self.select_lab = QtWidgets.QLabel(self.centralwidget)
        self.select_lab.setGeometry(QtCore.QRect(260, 80, 31, 16))
        self.select_lab.setObjectName("select_lab")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(560, 100, 75, 23))
        self.submit.setObjectName("submit")
        self.log_txt = QtWidgets.QTextBrowser(self.centralwidget)
        self.log_txt.setGeometry(QtCore.QRect(260, 401, 291, 181))
        self.log_txt.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.log_txt.setOpenLinks(True)
        self.log_txt.setObjectName("log_txt")
        self.pending_lab = QtWidgets.QLabel(self.centralwidget)
        self.pending_lab.setGeometry(QtCore.QRect(260, 130, 121, 16))
        self.pending_lab.setObjectName("pending_lab")
        self.log_lab = QtWidgets.QLabel(self.centralwidget)
        self.log_lab.setGeometry(QtCore.QRect(260, 380, 31, 16))
        self.log_lab.setObjectName("log_lab")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Abril Fatface")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.pendin_urls = QtWidgets.QTextEdit(self.centralwidget)
        self.pendin_urls.setGeometry(QtCore.QRect(260, 150, 291, 221))
        self.pendin_urls.setLineWidth(1)
        self.pendin_urls.setOverwriteMode(False)
        self.pendin_urls.setObjectName("pendin_urls")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(640, 100, 75, 23))
        self.stop.setObjectName("stop")
        self.saveurl = QtWidgets.QPushButton(self.centralwidget)
        self.saveurl.setGeometry(QtCore.QRect(560, 150, 75, 23))
        self.saveurl.setObjectName("saveurl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "笔趣阁爬虫"))
        self.select_lab.setText(_translate("MainWindow", "选择"))
        self.submit.setText(_translate("MainWindow", "开始"))
        self.pending_lab.setText(_translate("MainWindow", "待处理网址 一行一个"))
        self.log_lab.setText(_translate("MainWindow", "日志"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">欢迎使用笔趣阁爬虫程序，如果你在使用过程中有任何问题，请联系我</span></p></body></html>"))
        self.stop.setText(_translate("MainWindow", "停止"))
        self.saveurl.setText(_translate("MainWindow", "保存"))

